### ISSUE TITLE
Speedrun-viable build?

### ISSUE THREAD

**Issue by viiibe** [GTAmodding/re3#1114]
Come to think about it, it would be really cool if there was an effort to produce a speedrun-viable build of re3. Concessions would have to be made in order to bring this down to more parity with GTA III, but it could in turn potentially make for an easier way to set up the game for speedruns as older GTA games are just pain to set up properly at times. Plus attention from the speedrunning community could prove beneficial for discoveries regarding the accuracy of re3 compared to the original.

**Comment by withmorten** [comment]
There's a Vanilla config that is pretty much original gta3/gta-vc (except that it uses userfiles folder IIRC, and no movies and nasty game always), that should be sufficient.

It also compiles with the original IDE CodeWarrior 7, but last I tested that build was a bit unstable.

**Comment by Grovespaz** [comment]
It is doubtful the GTA speedrunning community would accept such a version for legit runs though.
There is too much potential of small differences making an impact on records, especially as long as physics (and their tedious tie-in to framerate) aren't completely understood yet.

It's not inconceivable that certain clips (at Diaz's mansion for example, or gatezip) would perform subtly differently on re3 using the same hardware.

The III/VC speedrunning community recently banned running with custom skins, because some skins using certain filename lengths would have an impact on the path of subways and planes. If they are that rigorous, re3 parity seems ways off and at that point, why not just play the original exe?

Then again, I'm not a speedrunner so it's not really my call, just weighing in.

**Comment by ZeptoBST** [comment]
A dedicated category could be created for it though.

**Comment by EnglishBen** [comment]
As Grovespaz said, this would never be something we use for speedruns because any type of unnecessary game modification is banned. Allowing overhauls like this would open a huge can of worms that is more effort than it's worth.

That being said, there might be merit to a category of glitchless runs that could use re3 due to a lot of the speedrun abuse being patched, however this would be something that is on the category extensions at maximum.
