### ISSUE TITLE
[reVC] Disable auto restore health after save game like in Grand Theft Auto III

### ISSUE THREAD

**Issue by YALdysse** [GTAmodding/re3#1196]
**Describe the bug**
It is not bug. I my openion, with disabled restoring health after save game playing is interesting.

**Version**
cb72fee9

**Comment by aeifr** [comment]
The main goal of the project is to restore the behavior of GTA III in its entirety. And next to that some improvements, like native shaders etc. And fixing bugs. Due to not being a bug nor an improvement, this can be achieved trough an not yet created toggle implementation or trough a fork of yours. 

If you desire such a feature, you might want to create a fork in the first run. As long as nothing changes the touched lines to disable health restoration, you could also get the changes applied to the master branch.

Feature requests like this would affect many peoples which do remember the intended behavior is differently to your suggestion. Which would not be compliant, as explained in the first paragraph.
