### ISSUE TITLE
[re3] Unable to place custom waypoint while control is taken away from player by script

### ISSUE THREAD

**Issue by NABN00B** [GTAmodding/re3#1239]
**Describe the bug**
When the script takes away the control from the player, custom waypoints cannot be toggled in the Map screen of the pause menu.

**To Reproduce**
Pause the game when control is taken away by an ingame cutscene (ie non-motion capture) and try to place a custom waypoint in the Map menu.

**Expected behavior**
We should be able to place/remove custom waypoints whenever it is possible to pause the game and access the Map.

**Screenshots**
n/a

**Version**
1.0

**Comment by asm95** [comment]
Are you sure this is GTA 3?

Do you know which mission this happens? I tried the first one in reVC and I could place the gray waypoint.

**Comment by davicr** [comment]
``CRadar::DrawBlips`` will never progress during cutscenes because the first conditional will never pass, as ``TheCamera.m_WideScreenOn`` will be ``true`` during cutscenes. Additionally, it might be ``true`` during cutscenes due to ``CCutsceneMgr::SetupCutsceneToStart``, however I have not investigated further yet.

**Comment by Sergeanur** [comment]
I merged the PR so this should be fixed.
