### ISSUE TITLE
Wrecked cars can explode again

### ISSUE THREAD

**Issue by erorcun** [GTAmodding/re3#251]
Explosion didn't appear in replay, but it was there (is that another bug?)

https://streamable.com/p6npp

**Comment by Nick007J** [comment]
In replay, health-related stuff is processed separately, so in this case in replay it was "handled" correctly it seems. There are cases when this is not the case. For example, if you record a replay with multiple wrecks, they will not be rendered as exploded at the start of a replay (because this flag is not saved in replay file), but instead they will be on fire for 5 seconds and then blow up (as a vehicle with 0 health) - unless the wreck was upside down.

**Comment by erorcun** [comment]
Oh then replay was ok, thanks but the car exploded twice in the game actually, and replay showed that correctly.
