### ISSUE TITLE
Trails broken on 64-bit D3D9 build

### ISSUE THREAD

**Issue by erorcun** [GTAmodding/re3#657]

**Comment by erorcun** [comment]
nvm, looks ok but some confirmation would be nice

**Comment by ttyborg** [comment]
Hello!

Trails effect is broken for me as well, on 64-bit opengl build for Linux, and opengl Windows binary through wine.
It happens when I set Anti-Aliasing either to 16x or 32x, so 8x and lower looks as it should. I don't know if it's related, or even relevant, but the d3d9 version only goes up to 16x AA. 
The d3d9 version also looks fine with wine.

**Comment by Calinou** [comment]
> t happens when I set Anti-Aliasing either to 16x or 32x, so 8x and lower looks as it should. I don't know if it's related, or even relevant, but the d3d9 version only goes up to 16x AA.

This is because graphics drivers often implement 16× MSAA as a mixture of SSAA and MSAA (or another fancy antialiasing method).

We should probably document this and tell people not to use MSAA above 8×.

**Comment by TRPB** [comment]
has this been disabled? I'd like to use 16x MSAA on linux but the maximum option is 8x.

**Comment by ttyborg** [comment]
I just downloaded the latest nightly, and I can go up to 32x.
