### ISSUE TITLE
Add project logo

### ISSUE THREAD

**Issue by hazelnot** [GTAmodding/re3#770]
This is pretty self-explanatory: the project doesn't have a logo! I made one (with two colour variations!) if you're interested in using it though!

I don't know how to properly propose a design to a GitHub project, which is why I made an issue instead of... however it's normally done. I apologize if I did something wrong. The zip file contains SVG versions of the logo as well.

[re3.zip](https://github.com/GTAmodding/re3/files/5395682/re3.zip)
![re3_logo](https://user-images.githubusercontent.com/10992973/96337700-902b6f00-1091-11eb-9118-3fc9331b5de3.png)
![re3_logo_2](https://user-images.githubusercontent.com/10992973/96337701-90c40580-1091-11eb-8fd7-ba0fcc0c90e0.png)

**Comment by hazelnot** [comment]
I made another version of the logo, this time with a subtle coloured outline similar to the one GTA III 10th Anniversary uses.
![re3_logo_o](https://user-images.githubusercontent.com/10992973/96351341-55dac580-10c3-11eb-9d55-7d8772ff5176.png)
![re3_logo_2_o](https://user-images.githubusercontent.com/10992973/96351342-56735c00-10c3-11eb-9751-db65967ea635.png)
[re3_o.zip](https://github.com/GTAmodding/re3/files/5396325/re3_o.zip)

**Comment by Tatsh** [comment]
I like this. Can you also provide a 1024x1024 icon with the text correctly placed? Would be for the icon on desktop platforms.

**Comment by hazelnot** [comment]
Sure, although I'm on Linux so if you need an actual .ico file I don't know if I can help 😅️

**Comment by hazelnot** [comment]
![re3_logo_o](https://user-images.githubusercontent.com/10992973/96361985-cbca4580-1132-11eb-960e-c11eb8fb8fd4.png)
![re3_logo_2_o](https://user-images.githubusercontent.com/10992973/96361987-cc62dc00-1132-11eb-99c1-5af8bfc5e982.png)

**Comment by Tatsh** [comment]
On Linux you can use ImageMagick to convert to ICO: https://stackoverflow.com/a/49823738/374110 (also I would add size 40 to the list).

Also consider if you want the smaller icons to be different rather than having every size be the exact same. See [Level of detail (MSDN)](https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-icons#level-of-detail), ["Maintain visual consistency in all icon sizes." (Apple)](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/#:~:text=Maintain%20visual%20consistency%20in%20all%20icon%20sizes.).

On macOS these are the widths/heights: 16, 32, 64, 128, 256, 512, 1024.

On Linux I presume you would want a .desktop file to use the SVG?

**Comment by hazelnot** [comment]
I don't think I can do the Apple icons cause they require some weird mathematical shapes that Apple only provides as Sketch, XD or Photoshop files and since I'm on Linux I don't have access to any of those programs. I can do the Windows icons though, and I'll attach the fixed (i.e. square and centered) SVGs here I guess.
[re3_fixed.zip](https://github.com/GTAmodding/re3/files/5397265/re3_fixed.zip)

**Comment by Tatsh** [comment]
If you want to make a pull request with this icon, you can replace `src/skel/win/gta3.ico` with your own ICO file (can only pick one). I would put the PNGs and SVGs in the `src/skel` directory.

This is a great thing because then the copyrighted icon currently being used goes away.

**Comment by hazelnot** [comment]
Alright then, I made the pull request!
